# Identifying And Comparison Analyze Impactful Pairs of Insertion Mutations in Proteins
# 2024
# Changrui Li and Yang Zheng

#PDB ID of protein that is being used
proteins: ['1crn','1csp','1hhp']

# Discovered metrics
metrics: [
  'cluster_configuration_entropy',
  'hbond_count',
  'size_of_largest_cluster',
  'rigidity_order_parameter'
  ]

# Path
saved_protein_data_path: '../data/saved_classes_data/'
